---
output: 
  word_document:
    reference_docx: word_styles-reference-itineraries.docx
params:
  type: 
    label: "Which Sampling Event"
    value: 5
    input: select
    choices: [1,2,3,4,5]
  grouping:
    label: "Which Basin or Grouping"
    value: Agawam
    input: select
    choices: [Delaware,Lower Hudson,Oneida,St. Lawrence, Oneida]
  user:
    label: "Who is generating these files?"
    value: 'amonion'
    input: select
    choices: ['amonion','mpkraft']
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(dplyr)
library(openxlsx)
library(dplyr)
library(gt)
#read in table types
fieldseason<-paste("C:/Users/",params$user,"/New York State Office of Information Technology Services/LMAS - LCI/2021.field.season.files/LCI.Field.Season.xlsx",sep="")
time<-read.xlsx(fieldseason,sheet = 3)
time$Time<-convertToDateTime(time$Time)
time$time.to.drive.to.next<-convertToDateTime(time$time.to.drive.to.next)
time$Trip.Total<-convertToDateTime(time$Trip.Total)
time$Day.Total<-convertToDateTime(time$Day.Total)
access<-read.xlsx(fieldseason, sheet =2)
float<-read.xlsx(fieldseason, sheet =4, detectDates = FALSE)
float$Departure<-convertToDateTime(float$Departure)
bottles<-read.xlsx(fieldseason, sheet =5)

#change type to MonthSampling
#change sample to Key
#change layer to InfoType
#change Lake to LOCATION_ID

#rename headers
colnames(bottles)[colnames(bottles)=="SiteID"]<-"LOCATION_ID"
#truncate
bottles<-unique(bottles[c('LOCATION_ID','MonthSampling','Key','InfoType','QCType')])
#remove QA samples
bottles<-bottles[bottles$LOCATION_ID!="none",]
bottles<-unique(bottles[c('LOCATION_ID','MonthSampling','Key','InfoType','QCType')])
#change type to trip
colnames(bottles)[colnames(bottles)=="MonthSampling"]<-"Trip"


#restrict and merge the tables
access<-unique(access[c('LOCATION_ID','Lake','Y_Coordinate','X_Coordinate','access.site_lat','access.site_lon','Access','needs.big.boat','motor','Depth','map')])
time$NA.<-NULL
itinerary<-merge(time,access,by=c('Lake'),all=TRUE)
itinerary<-merge(itinerary,float,by=c('basin','Trip','team','Day'),all = TRUE)
itinerary<-merge(itinerary,bottles,by=c('LOCATION_ID','Trip'),all=TRUE)
rm(list=c('access','time','float','bottles'))
itinerary$needs.big.boat<-ifelse(is.na(itinerary$needs.big.boat),"No",itinerary$needs.big.boat)
itinerary$motor<-ifelse(is.na(itinerary$motor),"No",itinerary$motor)
itinerary<-itinerary %>% 
  arrange(Trip,basin,team,Day,Order)
itinerary<-itinerary[!is.na(itinerary$basin),]
itinerary$Time<-gsub("1899-12-30 ","",itinerary$Time)
itinerary$time.to.drive.to.next<-gsub("1899-12-30 ","",itinerary$time.to.drive.to.next)
itinerary$Trip.Total<-gsub("1899-12-31 ","",itinerary$Trip.Total)
itinerary$Trip.Total<-gsub("1899-12-30 ","",itinerary$Trip.Total)
itinerary$Day.Total<-gsub("1899-12-30 ","",itinerary$Day.Total)



#################################################################################################################
#################################################################################################################
#################################################################################################################
#################################################################################################################
#################################################################################################################
#################################################################################################################
itinerary<-itinerary %>% 
  filter(Trip==params$type,
         basin==params$grouping)
#################################################################################################################
#################################################################################################################
#################################################################################################################
#################################################################################################################
#################################################################################################################
#################################################################################################################


itinerary<-itinerary %>% 
  arrange(Crew.Leader,Trip,basin,team,Day,Order)

```


```{r echo = FALSE, results = "asis", message=FALSE, warning=FALSE}
#try this: https://stackoverflow.com/questions/36674824/use-loop-to-generate-section-of-text-in-rmarkdown

template1 <- "##     page break\n
______________________________________________________________________________________\n
Trip: %s - Trip %s - Team %s\n
Time to travel to first site: %s\n
Trip total time: %s\n
These locations are stored on google map:\n
 https://tinyurl.com/y5eku8cg \n
\n
\n" 

template2 <- "......................................................................................\n
Day: %s (total time needed for the day: %s)\n
Team: %s, %s\n
Lake: %s (class %s)\n
Access location: %s, %s || Deep Hole: %s,%s || Max Depth: %s\n
Estimated Sampling Time: %s hours || Estimated time to travel to the next site: %s\n
Does it need a big boat: %s || Motor specifications: %s\n
Access Information: %s\n
map: %s\n
Samples to be collected:\n
\n
\n" # dont't forget the newline

template3 <- "......................................................................................\n
Day: %s (total time needed for the day: %s)\n
%s\n
Estimated 30 min to ship samples at UPS store and no time to travel to the hotel. \n
Time to next: %s\n
\n
\n" # dont't forget the newline





for (i in seq(nrow(itinerary))) {
  current <- itinerary[i, ]
  samplecurrent<-itinerary %>% filter(LOCATION_ID==current$LOCATION_ID,Trip==current$Trip) %>% select(Key,InfoType,QCType) %>% distinct()
  #use template 2 for every 10 records (includes a line break) and template 1 for all others
  if(is.na(current$class)){
    if(current$Lake=="Start"){
        cat(sprintf(template1, current$basin, current$Trip,current$team,current$time.to.drive.to.next,current$Trip.Total))
    }
    if(current$Lake!="Start"){
        cat(sprintf(template3, current$Day,current$Day.Total,current$Lake,current$time.to.drive.to.next))
    }
    }
  
  if(!is.na(current$class)){
    cat(sprintf(template2, current$Day,current$Day.Total,current$Crew.Leader,current$Crew.Members,current$Lake, current$class,current$access.site_lat,current$access.site_lon,current$Y_Coordinate,current$X_Coordinate,current$Depth,current$Time, current$time.to.drive.to.next, current$needs.big.boat, current$motor, current$Access,current$map))
    for(j in 1:nrow(samplecurrent)){
   cat("\n")
   print(paste(samplecurrent$Key[j],samplecurrent$InfoType[j],samplecurrent$QCType,sep="_"))
   cat("\n")
  }
  }
}



#rm(list=ls())
```
