---
output: 
  word_document:
    reference_docx: word_styles-reference-labels.docx
params:
  type: 
    label: "Which Sampling Event"
    value: Sample1
    input: select
    choices: [Sample1,Sample2,Sample3,Sample4,Sample5]
  grouping:
    label: "Which Basin or Grouping"
    value: Delaware
    input: select
    choices: [Delaware,DWSP2,Genesee,Lower Hudson,Oneida,St. Lawrence]
  user:
    label: "Who is generating these files?"
    value: 'amonion.000'
    input: select
    choices: ['amonion.000','mpkraft']
---

```{r setup, include=FALSE}

#Instructions on how to use:
#print the output to 255 but change the source to bypass and the paper to thick2
#place the label paper upside down and with the top towards the outside

knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(readxl)
#read in table types
fieldseason<-paste("C:/Users/",params$user,"/New York State Office of Information Technology Services/LMAS - LCI/LCI.Field.Season.xlsx",sep="")
bottles<-read_excel(fieldseason, sheet ="6.parameters")
intensive<-read_excel(fieldseason, sheet ="5.labels")

#realine the table
library(tidyr)
intensive <- intensive %>% 
  gather(type, sample, Sample1:Sample5)

#merge to create a list of labels
labels<-merge(bottles,intensive,by=c('class','layer'),all=TRUE)
library(dplyr)
labels<-labels %>% 
  filter(!is.na(sample),
         !is.na(Parameter)) %>% 
  arrange(type,sample,Parameter) 

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#specifying which to print
labels<-labels %>% 
  filter(type==params$type,
         basingrouping==params$grouping)
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
labels<-labels[order(labels$type,labels$sample,labels$Parameter),]
```


```{r echo = FALSE, results = "asis"}
#try this: https://stackoverflow.com/questions/36674824/use-loop-to-generate-section-of-text-in-rmarkdown

template1 <- "SampleID: %s\n
Name: %s\n
##     mm/dd/yyyy  hh:mm\n" # dont't forget the newline

template2 <- "%s\n"
template3 <- "### %s\n"

template4 <- "........................................\n
\n"
template5 <- "\n"


for (i in seq(nrow(labels))) {
  current <- labels[i, ]
  cat(sprintf(template1, current$sample, current$Lake))
  if(current$Parameter!="Diss TPO4 (in H2SO4)FILTRD"&&current$Parameter!="Chl A, Vol Filtered:____________"&&current$Parameter!="DOC (in H2SO4)FILTERED"&&current$Parameter!="TDS FILTERED"){
    cat(sprintf(template2,current$Parameter))
    }
  if(current$Parameter=="Diss TPO4 (in H2SO4)FILTRD"|current$Parameter=="Chl A, Vol Filtered:____________"|current$Parameter=="DOC (in H2SO4)FILTERED"|current$Parameter=="TDS FILTERED"){
    cat(sprintf(template3,current$Parameter))
    }
  cat(sprintf(template4))
}
```
