---
output: 
  word_document:
    reference_docx: word_styles-reference-baglabels.docx
params:
  type: 
    label: "Which Sampling Event"
    value: Sample2
    input: select
    choices: [Sample2,Sample3,Sample4,Sample5]
  grouping:
    label: "Which Basin or Grouping"
    value: Delaware
    input: select
    choices: [Delaware,DWSP2,Genesee,Lower Hudson,Oneida,St. Lawrence]
  user:
    label: "Who is generating these files?"
    value: 'amonion.000'
    input: select
    choices: ['amonion.000','mpkraft']
---

```{r setup, include=FALSE}

#Instructions on how to use:
#print the output to 255 but change the source to bypass and the paper to thick2
#place the label paper upside down and with the top towards the outside

knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(readxl)
#read in table types
fieldseason<-paste("C:/Users/",params$user,"/New York State Office of Information Technology Services/LMAS - LCI/LCI.Field.Season.xlsx",sep="")
bottles<-read_excel(fieldseason, sheet ="6.parameters")
intensive<-read_excel(fieldseason, sheet ="5.labels")

#realine the table
library(tidyr)
intensive <- intensive %>% 
  gather(type, sample, Sample1:Sample4)

baglabels<-intensive[order(intensive$type,intensive$sample),]

#add bottle number
baglabels$bottles<-NA
baglabels$bottles<-ifelse(baglabels$class=="A"|baglabels$class=="Oneida",ifelse(baglabels$layer=="epi",9,7),ifelse(baglabels$layer=="epi",8,7))
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#specifying which to print
baglabels<-baglabels[baglabels$type=="Sample1",]
baglabels<-baglabels[baglabels$basingrouping=="Washington Park",]
#baglabels<-baglabels[baglabels$class=="Oneida",]
#baglabels<-baglabels[baglabels$Parameter=="TOC (in H2SO4)",]
#baglabels<-baglabels[baglabels$basingrouping=="QA",]
#baglabels<-baglabels[baglabels$Lake=="Muskellunge Lake",]
#baglabels<-baglabels[baglabels$class=="Oneida",]
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

baglabels<-baglabels[order(baglabels$type,baglabels$sample),]
```


```{r echo = FALSE, results = "asis"}
#try this: https://stackoverflow.com/questions/36674824/use-loop-to-generate-section-of-text-in-rmarkdown

template1 <- "SampleID: %s\n
Name: %s\n
Type: %s, class %s\n
%s, %s bottles\n
## ..............................\n
\n" # dont't forget the newline

template2 <- "SampleID: %s\n
Name: %s\n
Type: %s, class %s\n
%s, %s bottles\n
\n" # dont't forget the newline




for (i in seq(nrow(baglabels))) {
  current <- baglabels[i, ]
  #use template 2 for every 10 records (includes a line break) and template 1 for all others
  j<-i/10
  if(j%%1==0){
    cat(sprintf(template2, current$sample, current$Lake, current$layer,current$class,current$type,current$bottles))
    }
  
  if(j%%1!=0){
    cat(sprintf(template1, current$sample, current$Lake, current$layer,current$class,current$type,current$bottles))
    }
}

rm(list=ls())
```
